# -*- encoding : utf-8 -*-
class Card; module Set; class Abstract; module CodePointer; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/abstract/code_pointer.rb ~~
include_set Abstract::Pointer

abstract_basket :item_codenames

def raw_content
  item_codenames.map do |codename|
    Card[codename] && Card[codename].name
  end.compact.to_pointer_content
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/abstract/code_pointer.rb ~~
end;end;end;end;
