# -*- encoding : utf-8 -*-
class Card; module Set; module Type; module LayoutType; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/type/layout_type.rb ~~~~~~~~~~~
# -*- encoding : utf-8 -*-
include Html

format do
  include Html::Format
end

format :html do
  include Html::HtmlFormat

  view :core do |args|
    with_inclusion_mode :template do
      process_content ::CodeRay.scan( _render_raw, :html ).div
    end
  end
end

# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/type/layout_type.rb ~~~~~~~~~~~
end;end;end;end;
