# -*- encoding : utf-8 -*-
class Card; module Set; module Type; module Toggle; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/type/toggle.rb ~~~~~~~~~~~

view :core do |args|
  case card.raw_content.to_i
  when 1; 'yes'
  when 0; 'no'
  else  ; '?'
  end
end

view :editor do |args|
  check_box :content
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/type/toggle.rb ~~~~~~~~~~~
end;end;end;end;
