# -*- encoding : utf-8 -*-
class Card; module Set; class Type; module LayoutType; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/type/layout_type.rb ~~
# -*- encoding : utf-8 -*-
include_set Type::Html

format :html do
  view :core do |_args|
    with_nest_mode :template do
      process_content ::CodeRay.scan(_render_raw, :html).div
    end
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/type/layout_type.rb ~~
end;end;end;end;
