# -*- encoding : utf-8 -*-
class Card; module Set; class Type; module Phrase; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/type/phrase.rb ~~
view :editor do |_args|
  text_field :content, class: "card-content"
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/type/phrase.rb ~~
end;end;end;end;
