# -*- encoding : utf-8 -*-
class Card; module Set; class Type; module Toggle; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/type/toggle.rb ~~

view :core do |_args|
  case card.raw_content.to_i
  when 1 then "yes"
  when 0 then "no"
  else; "?"
  end
end

view :editor do |_args|
  check_box :content
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/type/toggle.rb ~~
end;end;end;end;
