# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Delete; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/delete.rb ~~
include_set Abstract::Permission


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/delete.rb ~~
end;end;end;end;
