# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Read; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/read.rb ~~
include Abstract::Permission

format :html do include Abstract::Permission::HtmlFormat end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/read.rb ~~
end;end;end;end;
