# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Help; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/help.rb ~~
extend Card::Setting
setting_opts group: :editing_cue, position: 1, rule_type_editable: true


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/help.rb ~~
end;end;end;end;
