# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module OnDelete; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/on_delete.rb ~~
extend Card::Setting
setting_opts group: :event, position: 3, rule_type_editable: false


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/on_delete.rb ~~
end;end;end;end;
