# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Update; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/update.rb ~~
extend Card::Setting
setting_opts group: :permission, position: 3, rule_type_editable: false


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/update.rb ~~
end;end;end;end;
