# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Follow; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/self/follow.rb ~~
extend Card::Setting
setting_opts group: :other, position: 7, rule_type_editable: false, user_specific: true


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/self/follow.rb ~~
end;end;end;end;
