# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Never; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/self/never.rb ~~
include Card::FollowOption

follow_opts position: 3

follow_test { |_follower_id, _accounted_ids| false }

def title
  "Ignoring"
end

def label
  "ignore"
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/self/never.rb ~~
end;end;end;end;
