# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptCardMenu; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/script_card_menu.rb ~~
include_set Abstract::CodeFile


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/script_card_menu.rb ~~
end;end;end;end;
