# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module StyleJqueryUiSmoothness; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/style_jquery_ui_smoothness.rb ~~
include_set Abstract::CodeFile


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/style_jquery_ui_smoothness.rb ~~
end;end;end;end;
