# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module StyleBootstrapCompatible; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/style_bootstrap_compatible.rb ~~
include_set Abstract::CodeFile


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/style_bootstrap_compatible.rb ~~
end;end;end;end;
