# -*- encoding : utf-8 -*-
class Card; module Set; class Type; module Pointer; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/type/pointer.rb ~~
include_set Abstract::Pointer


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/type/pointer.rb ~~
end;end;end;end;
