# -*- encoding : utf-8 -*-
class Card; module Set; module Type; module JavaScript; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/type/java_script.rb ~~~~~~~~~~~
# -*- encoding : utf-8 -*-
require 'uglifier'

include Machine
include MachineInput

store_machine_output filetype: "js"

machine_input do
  Uglifier.compile(format(:js)._render_core)
end

def clean_html?
  false
end


format do
  def chunk_list  #turn off autodetection of uri's
    :inclusion_only
  end
end

format :html do
  view :editor, mod: Html::HtmlFormat
  view :content_changes, mod: CoffeeScript::HtmlFormat

  view :core do |args|
    highlighted_js = ::CodeRay.scan( _render_raw, :js ).div
    process_content highlighted_js
  end

end

def diff_args
   {format: :text}
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/type/java_script.rb ~~~~~~~~~~~
end;end;end;end;
