# -*- encoding : utf-8 -*-
class Card; module Set; module Type; module Scss; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/type/scss.rb ~~~~~~~~~~~
include Type::Css

def diff_args
  {format: :text}
end

format do
  include Css::Format

  view :core do |args|
    compile_scss(process_content _render_raw)
  end

  def compile_scss scss, style=:expanded
    Sass.compile scss, style: style
  rescue =>e
    e
  end

end

format( :html ) { include Css::HtmlFormat }


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/type/scss.rb ~~~~~~~~~~~
end;end;end;end;
