# -*- encoding : utf-8 -*-
class Card; module Set; module Type; module Skin; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/type/skin.rb ~~~~~~~~~~~
include Machine
include MachineInput

store_machine_output filetype: "css"

include Pointer
format()      { include Pointer::Format     }
format(:html) { include Pointer::HtmlFormat }
format(:css ) { include Pointer::CssFormat  }





# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/type/skin.rb ~~~~~~~~~~~
end;end;end;end;
