# -*- encoding : utf-8 -*-
class Card; module Set; class All; module RichBootstrap; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/all/rich_bootstrap.rb ~~
format :html do
  view :closed do |args|
    args[:body_class] = "closed-content"
    super args
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/all/rich_bootstrap.rb ~~
end;end;end;end;
