# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Captcha; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/captcha.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts group: :permission, position: 5


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/captcha.rb ~~~~~~~~~~~
end;end;end;end;
