# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Create; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/create.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts group: :permission, position: 1, rule_type_editable: false


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/create.rb ~~~~~~~~~~~
end;end;end;end;
