# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Default; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/default.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts :group=> :templating, :position=>2, :rule_type_editable => true


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/default.rb ~~~~~~~~~~~
end;end;end;end;
