# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module OptionsLabel; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/options_label.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts group: :pointer, position: 2, restricted_to_type: [:pointer,:session], rule_type_editable: false


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/options_label.rb ~~~~~~~~~~~
end;end;end;end;
