# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Style; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/style.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts :group=>:webpage, :position=>4


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/style.rb ~~~~~~~~~~~
end;end;end;end;
