# -*- encoding : utf-8 -*-
class Card; module Set; class All; module LocationHistory; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/core/set/all/location_history.rb ~~
event :discard_deleted_locations, in: :finalize, on: :delete do
  Env.discard_locations_for self
  success.target = :previous if success.target == self
end

event :save_current_location, before: :show_page, on: :read do
  Env.save_location self
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/core/set/all/location_history.rb ~~
end;end;end;end;
