# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module AddHelp; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/add_help.rb ~~
format :html do
  view :core do |args|
    with_nest_mode :template do
      super args
    end
  end

  view :closed_content do |_args|
    "#{_render_type} : #{_render_raw}"
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/add_help.rb ~~
end;end;end;end;
