# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Default; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/default.rb ~~
format :html do
  include AddHelp::HtmlFormat
end

def empty_ok?
  true
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/default.rb ~~
end;end;end;end;
