# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Help; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/help.rb ~~
format :html do
  include AddHelp::HtmlFormat
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/help.rb ~~
end;end;end;end;
