# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Update; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/update.rb ~~
include_set Abstract::Permission


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/right/update.rb ~~
end;end;end;end;
