# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptMods; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/self/script_mods.rb ~~
include_set Abstract::CodePointer


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/self/script_mods.rb ~~
end;end;end;end;
