# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptPointerConfig; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/self/script_pointer_config.rb ~~
include_set Abstract::CodeFile

Self::ScriptEditors.add_to_basket :item_codenames, :script_pointer_config


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/pointer/set/self/script_pointer_config.rb ~~
end;end;end;end;
