# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module ScriptHtml5shivPrintshiv; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/script_html5shiv_printshiv.rb ~~~~~~~~~~~
format { include ScriptAce::Format }
format(:html) { include ScriptAce::HtmlFormat }


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/script_html5shiv_printshiv.rb ~~~~~~~~~~~
end;end;end;end;
