# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module ScriptAce; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/script_ace.rb ~~~~~~~~~~~

view :raw do |args|
  
  Rails.logger.info "reading file: #{Cardio.gem_root}/mod/03_machines/lib/javascript/#{card.codename}.js"
  File.read "#{Cardio.gem_root}/mod/03_machines/lib/javascript/#{card.codename}.js"
end

format :html do
  view :editor do |args|
    "Content is stored in file and can't be edited."
  end
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/script_ace.rb ~~~~~~~~~~~
end;end;end;end;
