# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module StyleJqueryUiSmoothness; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/style_jquery_ui_smoothness.rb ~~~~~~~~~~~
format { include StyleBootstrapCompatible::Format }
format(:html) { include ScriptAce::HtmlFormat }



# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/style_jquery_ui_smoothness.rb ~~~~~~~~~~~
end;end;end;end;
