# -*- encoding : utf-8 -*-
class Card; module Set; class Type; module Scss; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/type/scss.rb ~~
include_set Type::Css

format do
  view :core do |_args|
    compile_scss(process_content _render_raw)
  end

  def compile_scss scss, style=:expanded
    Sass.compile scss, style: style
  rescue Sass::SyntaxError => e
    raise Card::Error, "Sass::SyntaxError (#{card.name}:#{e.sass_line}): " \
                       "#{e.message}"
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/type/scss.rb ~~
end;end;end;end;
