# -*- encoding : utf-8 -*-
class Card; module Set; class Type; module Skin; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/type/skin.rb ~~
include Machine
include MachineInput

store_machine_output filetype: "css"

include_set Pointer


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/type/skin.rb ~~
end;end;end;end;
