# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module ScriptJquery; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/script_jquery.rb ~~~~~~~~~~~
format { include ScriptAce::Format }
format(:html) { include ScriptAce::HtmlFormat }


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/script_jquery.rb ~~~~~~~~~~~
end;end;end;end;
