# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module StyleCards; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/style_cards.rb ~~~~~~~~~~~

view :raw do |args|
  File.read "#{Cardio.gem_root}/mod/03_machines/lib/stylesheets/style_cards.scss"
end

format(:html) { include ScriptAce::HtmlFormat }


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/03_machines/set/self/style_cards.rb ~~~~~~~~~~~
end;end;end;end;
