# -*- encoding : utf-8 -*-
class Card; module Set; module All; module EmailHtml; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/all/email_html.rb ~~~~~~~~~~~
format :email_html do
  view :missing        do |args| '' end
  view :closed_missing do |args| '' end
end



# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/all/email_html.rb ~~~~~~~~~~~
end;end;end;end;
