# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Alerts; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/self/alerts.rb ~~~~~~~~~~~

view :raw do |args|
  '<!-- *alerts is deprecated. please remove from layout -->'
end
view :core, :raw


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/self/alerts.rb ~~~~~~~~~~~
end;end;end;end;
