# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Foot; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/self/foot.rb ~~~~~~~~~~~

format :html do
  view :raw do |args|
    '<!-- *foot is deprecated. please remove from layout -->'
  end

  view :core, :raw
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/self/foot.rb ~~~~~~~~~~~
end;end;end;end;
