# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Now; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/self/now.rb ~~~~~~~~~~~

view :raw do |args|
  Time.now.strftime '%A, %B %d, %Y %I:%M %p %Z'
end

view :core, :raw


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/self/now.rb ~~~~~~~~~~~
end;end;end;end;
