# -*- encoding : utf-8 -*-
class Card; module Set; module All; module AllJs; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/all/all_js.rb ~~~~~~~~~~~
    
format :js do
  view :include_tag do |args|
    %{\n#{javascript_include_tag page_path(card.cardname) }\n }
  end
  
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/all/all_js.rb ~~~~~~~~~~~
end;end;end;end;
