# -*- encoding : utf-8 -*-
class Card; module Set; module All; module Erb; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set/all/erb.rb ~~~~~~~~~~~
format do
  def render_erb locals={}, template=nil, a_binding=nil, &block
    template ||= block.call
    a_binding ||= binding
    locals.each do |k,v|
      #a_binding.local_variable_set(k, v) # needs ruby 2.1
      instance_variable_set("@#{k}",v)
    end
    ERB.new(template,nil,'-').result(binding)
  end
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set/all/erb.rb ~~~~~~~~~~~
end;end;end;end;
