# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptProsemirrorConfig; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/prosemirror_editor/set/self/script_prosemirror_config.rb ~~
include_set Abstract::CodeFile

Self::ScriptEditors.add_to_basket :item_codenames, :script_prosemirror_config
Self::Head::Javascript::HtmlFormat.add_to_basket(
  :mod_js_config, [:prose_mirror, "setProseMirrorConfig"]
)


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/prosemirror_editor/set/self/script_prosemirror_config.rb ~~
end;end;end;end;
