# -*- encoding : utf-8 -*-
class Card; module Set; class All; module AllJs; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/basic_formats/set/all/all_js.rb ~~

format :js do
  view :include_tag do |_args|
    %(\n#{javascript_include_tag page_path(card.cardname)}\n )
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/basic_formats/set/all/all_js.rb ~~
end;end;end;end;
