# -*- encoding : utf-8 -*-
class Card; module Set; class All; module File; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/basic_formats/set/all/file.rb ~~
format :file do
  view :core do |_args|
    "File rendering of this card not yet supported"
  end

  view :style do |_args|
    nil
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/basic_formats/set/all/file.rb ~~
end;end;end;end;
