# -*- encoding : utf-8 -*-
class Card; module Set; class All; module Text; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/basic_formats/set/all/text.rb ~~

format :text do
  view :core do |args|
    HTMLEntities.new.decode strip_tags(super args).to_s # need this string method to get out of html_safe mode
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/basic_formats/set/all/text.rb ~~
end;end;end;end;
