# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module AddHelp; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/add_help.rb ~~~~~~~~~~~
format :html do
  view :core do |args|
    with_inclusion_mode :template do
      super args
    end
  end
  
  view :closed_content do |args|
    "#{_render_type} : #{_render_raw}"
  end
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/add_help.rb ~~~~~~~~~~~
end;end;end;end;
