# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module Default; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/default.rb ~~~~~~~~~~~
format :html do
  include AddHelp::HtmlFormat
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/default.rb ~~~~~~~~~~~
end;end;end;end;
