# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module Delete; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/delete.rb ~~~~~~~~~~~
include Abstract::Permission

format :html do include Abstract::Permission::HtmlFormat end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/delete.rb ~~~~~~~~~~~
end;end;end;end;
