# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module Style; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/style.rb ~~~~~~~~~~~
require 'sass'
include Machine

store_machine_output filetype: "css"

format do
  def chunk_list  #turn off autodetection of uri's
    :inclusion_only
  end
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/right/style.rb ~~~~~~~~~~~
end;end;end;end;
