# -*- encoding : utf-8 -*-
class Card; module Set; module All; module ViewCache; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set/all/view_cache.rb ~~~~~~~~~~~
event :clear_view_cache, after: :store do
  Card::ViewCache.reset
end

format do
  def view_caching?
    false
  end
end

# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set/all/view_cache.rb ~~~~~~~~~~~
end;end;end;end;
