# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Salt; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/account/set/right/salt.rb ~~
include All::Permissions::Accounts

view :raw do |_args|
  "Private data"
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/account/set/right/salt.rb ~~
end;end;end;end;
