# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module BootstrapCards; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/06_bootstrap/set/self/bootstrap_cards.rb ~~~~~~~~~~~
view :raw do |args|
  File.read "#{Cardio.gem_root}/mod/06_bootstrap/lib/stylesheets/#{card.codename}.scss"
end

format :html do
  view :editor do |args|
    "Content is stored in file and can't be edited."
  end
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/06_bootstrap/set/self/bootstrap_cards.rb ~~~~~~~~~~~
end;end;end;end;
