# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module SmartmenuJs; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/06_bootstrap/set/self/smartmenu_js.rb ~~~~~~~~~~~
view :raw do |args|
  File.read "#{Cardio.gem_root}/mod/06_bootstrap/lib/javascript/smartmenu.js"
end

view :editor do |args|
  "Content is stored in file and can't be edited."
end

# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/06_bootstrap/set/self/smartmenu_js.rb ~~~~~~~~~~~
end;end;end;end;
