# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptProsemirror; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/prosemirror_editor/set/self/script_prosemirror.rb ~~
include_set Abstract::CodeFile

Self::ScriptMods.add_to_basket :item_codenames, :script_prosemirror


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/prosemirror_editor/set/self/script_prosemirror.rb ~~
end;end;end;end;
