# -*- encoding : utf-8 -*-
class Card; module Set; class Abstract; module ProsemirrorEditor; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/prosemirror_editor/set/abstract/prosemirror_editor.rb ~~
format :html do
  view :editor do |_args|
    wrap_with(:div, id: unique_id, class: "prosemirror-editor") do
      hidden_field(:content, class: "card-content", value: card.raw_content)
    end
  end
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/prosemirror_editor/set/abstract/prosemirror_editor.rb ~~
end;end;end;end;
