# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Accountable; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/accountable.rb ~~
require_dependency "card/setting"
extend Card::Setting
setting_opts group: :other, position: 2


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/accountable.rb ~~
end;end;end;end;
