# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Autoname; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/autoname.rb ~~
extend Card::Setting
setting_opts group: :templating, position: 3


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/autoname.rb ~~
end;end;end;end;
