# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Captcha; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/captcha.rb ~~
extend Card::Setting
setting_opts group: :permission, position: 5


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/captcha.rb ~~
end;end;end;end;
