# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module DefaultHtmlView; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/default_html_view.rb ~~
extend Card::Setting
setting_opts group: :other, position: 4, rule_type_editable: false


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/default_html_view.rb ~~
end;end;end;end;
