# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module FollowFields; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/follow_fields.rb ~~
extend Card::Setting
setting_opts group: :other, position: 5, rule_type_editable: false


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/follow_fields.rb ~~
end;end;end;end;
