# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Layout; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/layout.rb ~~
extend Card::Setting
setting_opts group: :webpage, position: 3, rule_type_editable: false


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/layout.rb ~~
end;end;end;end;
