# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Options; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/options.rb ~~
extend Card::Setting
setting_opts group: :pointer, position: 1,
             restricted_to_type: [:pointer, :session],
             rule_type_editable: true


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/options.rb ~~
end;end;end;end;
