# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module OptionsLabel; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/options_label.rb ~~
extend Card::Setting
setting_opts group: :pointer, position: 2,
             restricted_to_type: [:pointer, :session],
             rule_type_editable: false


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/options_label.rb ~~
end;end;end;end;
