# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module RecentSettings; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/recent_settings.rb ~~
def followable?
  false
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/recent_settings.rb ~~
end;end;end;end;
