# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Structure; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/structure.rb ~~
extend Card::Setting
setting_opts group: :templating, position: 2, rule_type_editable: true


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/structure.rb ~~
end;end;end;end;
