# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Style; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/style.rb ~~
extend Card::Setting
setting_opts group: :webpage, position: 4


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/settings/set/self/style.rb ~~
end;end;end;end;
