# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module MachineCache; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/right/machine_cache.rb ~~
def history?
  false
end

def followable?
  false
end

def clean_html?
  false
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/right/machine_cache.rb ~~
end;end;end;end;
