# -*- encoding : utf-8 -*-
class Card; module Set; module Type; module Html; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/type/html.rb ~~~~~~~~~~~
def clean_html?
  false
end

def diff_args
 {:format=>:raw}
end

format do
  view :closed_content do |args|
    ''
  end

  def chunk_list
    :references
  end
end


format :html do
  view :editor do |args|
    text_area :content, :rows=>5, :class=>'card-content ace-editor-textarea', "data-card-type-code"=>card.type_code
  end
end





# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/type/html.rb ~~~~~~~~~~~
end;end;end;end;
