# -*- encoding : utf-8 -*-
class Card; module Set; class All; module EmailText; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/all/email_text.rb ~~

format :email_text do
  view :missing        do |_args| "" end
  view :closed_missing do |_args| "" end
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/all/email_text.rb ~~
end;end;end;end;
