# -*- encoding : utf-8 -*-
class Card; module Set; class All; module SolidCache; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/solid_cache/set/all/solid_cache.rb ~~
def solid_cache?
  respond_to?(:solid_cache_card)
end

module ClassMethods
  def clear_solid_cache
    Auth.as_bot do
      Card.search(right: { codename: "solid_cache" }).each do |card|
        card.update_columns trash: true
        card.expire
      end
    end
  end
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/solid_cache/set/all/solid_cache.rb ~~
end;end;end;end;
