# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Alerts; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/self/alerts.rb ~~

view :raw do |_args|
  "<!-- *alerts is deprecated. please remove from layout -->"
end
view :core, :raw


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/self/alerts.rb ~~
end;end;end;end;
