# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Codenames; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/self/codenames.rb ~~


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/self/codenames.rb ~~
end;end;end;end;
