# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Foot; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/self/foot.rb ~~

format :html do
  view :raw do |_args|
    "<!-- *foot is deprecated. please remove from layout -->"
  end

  view :core, :raw
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/self/foot.rb ~~
end;end;end;end;
