# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Discussion; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/right/discussion.rb ~~
def show_comment_box_in_related?
  true
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/standard/set/right/discussion.rb ~~
end;end;end;end;
