# -*- encoding : utf-8 -*-
class Card; module Set; module All; module File; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/all/file.rb ~~~~~~~~~~~

format :file do

  view :core do |args|
    'File rendering of this card not yet supported'
  end
  
    
  view :style do |args|
    nil
  end
  
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/all/file.rb ~~~~~~~~~~~
end;end;end;end;
