# -*- encoding : utf-8 -*-
class Card; module Set; module All; module Text; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/all/text.rb ~~~~~~~~~~~

format :text do

  view :core do |args|
    HTMLEntities.new.decode "#{ strip_tags( super args ) }" #need this string method to get out of html_safe mode
  end

end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/02_basic_types/set/all/text.rb ~~~~~~~~~~~
end;end;end;end;
