# -*- encoding : utf-8 -*-
class Card; module Set; class All; module Bootstrap; module Wrapper; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/all/bootstrap/wrapper.rb ~~
format :html do
  def frame args={}, &_block
    args.reverse_merge!(
      panel_class:  "panel panel-default",
      header_class: "panel-heading",
      title_class:  "panel-title",
      body_class:   "panel-body"
    )
    super args
  end
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/all/bootstrap/wrapper.rb ~~
end;end;end;end;end;
