# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module MachineInput; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/right/machine_input.rb ~~
def followable?
  false
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/right/machine_input.rb ~~
end;end;end;end;
