# -*- encoding : utf-8 -*-
class Card::AllSet < Card::SetPattern
  cattr_accessor :options
  class << self
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set_pattern/01_all.rb ~~~~~~~~~~~

def label name
  'All cards'
end

def prototype_args anchor
  {}
end

def follow_label name
  'everything'
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set_pattern/01_all.rb ~~~~~~~~~~~
  end
  register "all", (options || {})
end

