# -*- encoding : utf-8 -*-
class Card::Set::All < Card::Set::Pattern
  cattr_accessor :options
  class << self
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/core/set_pattern/01_all.rb ~~

def label _name
  "All cards"
end

def prototype_args _anchor
  {}
end

def follow_label _name
  "everything"
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/core/set_pattern/01_all.rb ~~
  end
  register "all", (options || {})
end

