# -*- encoding : utf-8 -*-
class Card::AllPlusSet < Card::SetPattern
  cattr_accessor :options
  class << self
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/010_core/set_pattern/02_all_plus.rb ~~~~~~~~~~~

@@options = { junction_only: true }

def label _name
  'All "+" cards'
end

def prototype_args _anchor
  { name: "+" }
end

def follow_label _name
  'all "+" cards'
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/010_core/set_pattern/02_all_plus.rb ~~~~~~~~~~~
  end
  register "all_plus", (options || {})
end

