# -*- encoding : utf-8 -*-
class Card::StarSet < Card::SetPattern
  cattr_accessor :options
  class << self
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set_pattern/04_star.rb ~~~~~~~~~~~

def label name
  'All "*" cards'
end

def prototype_args anchor
  { :name=>'*dummy' }
end

def pattern_applies? card
  card.cardname.star?
end

def follow_label name
  'all "*" cards'
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/01_core/set_pattern/04_star.rb ~~~~~~~~~~~
  end
  register "star", (options || {})
end

