# -*- encoding : utf-8 -*-
class Card::RstarSet < Card::SetPattern
  cattr_accessor :options
  class << self
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/010_core/set_pattern/05_rstar.rb ~~~~~~~~~~~

@@options = { junction_only: true }

def label _name
  'All "+*" cards'
end

def prototype_args _anchor
  { name: "*dummy+*dummy" }
end

def pattern_applies? card
  card.cardname.rstar?
end

def follow_label _name
  'all "+*" cards'
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/010_core/set_pattern/05_rstar.rb ~~~~~~~~~~~
  end
  register "rstar", (options || {})
end

