# -*- encoding : utf-8 -*-
class Card::Set::Right < Card::Set::Pattern::Abstract
  cattr_accessor :options
  class << self
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/core/set_pattern/06_right.rb ~~

@@options = {
  junction_only: true,
  assigns_type: true
}

def label name
  %(All "+#{name}" cards)
end

def prototype_args anchor
  { name: "*dummy+#{anchor}" }
end

def anchor_name card
  card.cardname.tag
end

def follow_label name
  %(all "+#{name}s")
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/core/set_pattern/06_right.rb ~~
  end
  register "right", (options || {})
end

