# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module BootstrapCards; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/bootstrap_cards.rb ~~
include_set Abstract::CodeFile


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/bootstrap_cards.rb ~~
end;end;end;end;
