# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module BootstrapJs; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/bootstrap_js.rb ~~
include_set Abstract::CodeFile

def source_files
  %w(bootstrap.js bootstrap_modal_wagn.js)
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/bootstrap_js.rb ~~
end;end;end;end;
