# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptMods; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/script_mods.rb ~~
add_to_basket :item_codenames, :bootstrap_js

# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/script_mods.rb ~~
end;end;end;end;
