# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module SmartmenuCss; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/smartmenu_css.rb ~~
include_set Abstract::CodeFile

def source_files
  "startmenu.css"
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/bootstrap/set/self/smartmenu_css.rb ~~
end;end;end;end;
