# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module HtmlMessage; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/right/html_message.rb ~~~~~~~~~~~
def clean_html?
  false
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/right/html_message.rb ~~~~~~~~~~~
end;end;end;end;
