# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Edited; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/self/edited.rb ~~~~~~~~~~~
include Card::FollowOption

self.restrictive_follow_opts position: 2

self.follower_candidate_ids do |card|
  # FIXME? - could optimize by not using cards table...
  Card.search editor_of: card.name, return: :id
end


def title
  'Following content you edited'
end

def label
  "follow if I edited"
end

def description set_card
  "#{set_card.follow_label} I edited"
end





# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/self/edited.rb ~~~~~~~~~~~
end;end;end;end;
