# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Follow; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/self/follow.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts :group=>:other, :position=>7, :rule_type_editable => false, :user_specific=>true


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/self/follow.rb ~~~~~~~~~~~
end;end;end;end;
