# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Never; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/self/never.rb ~~~~~~~~~~~
include Card::FollowOption

self.follow_opts :position=>3

self.follow_test { |follower_id, accounted_ids| false }


def title
  'Ignoring'
end

def label
  'ignore'
end



# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_email/set/self/never.rb ~~~~~~~~~~~
end;end;end;end;
