# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module Cc; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/cc.rb ~~
include Bcc
format(:email_text) { include Bcc::EmailTextFormat }
format(:html)       { include Bcc::HtmlFormat }


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/cc.rb ~~
end;end;end;end;
