# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module FollowFields; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/follow_fields.rb ~~
event :follow_fields_changed, :integrate do
  Card.follow_caches_expired
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/follow_fields.rb ~~
end;end;end;end;
