# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module From; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/from.rb ~~
include Bcc
format(:email_text) { include Bcc::EmailTextFormat }
format(:html)       { include Bcc::HtmlFormat }


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/from.rb ~~
end;end;end;end;
