# -*- encoding : utf-8 -*-
class Card; module Set; class Right; module HtmlMessage; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/html_message.rb ~~
def clean_html?
  false
end


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/email/set/right/html_message.rb ~~
end;end;end;end;
