# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptSlot; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/script_slot.rb ~~
include_set Abstract::CodeFile

def source_files
  %w(wagn_mod wagn_editor wagn_layout wagn_navbox wagn_upload wagn).map do |n|
    "#{n}.js.coffee"
  end
end


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/machines/set/self/script_slot.rb ~~
end;end;end;end;
