# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Autoname; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/autoname.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts :group=>:templating, :position=>3


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/autoname.rb ~~~~~~~~~~~
end;end;end;end;
