# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module Read; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/read.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts :group=> :permission, :position=>2, :rule_type_editable=>false


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/read.rb ~~~~~~~~~~~
end;end;end;end;
