# -*- encoding : utf-8 -*-
class Card; module Set; module Self; module TableOfContents; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/table_of_contents.rb ~~~~~~~~~~~
extend Card::Setting
setting_opts :group=> :other, :position=>1, :rule_type_editable=>false


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/04_settings/set/self/table_of_contents.rb ~~~~~~~~~~~
end;end;end;end;
