# -*- encoding : utf-8 -*-
class Card; module Set; module All; module RichBootstrap; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/06_bootstrap/set/all/rich_bootstrap.rb ~~~~~~~~~~~
format :html do

  view :closed do |args|
    args.merge! body_class: 'closed-content'
    super args
  end

end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/06_bootstrap/set/all/rich_bootstrap.rb ~~~~~~~~~~~
end;end;end;end;
