# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module Version; extend Card::Set
# ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/admin/set/self/version.rb ~~
# -*- encoding : utf-8 -*-
require_dependency "card/version"

view :raw do |_args|
  Card::Version.release
end

view :core, :raw


# ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/admin/set/self/version.rb ~~
end;end;end;end;
