# -*- encoding : utf-8 -*-
class Card; module Set; class Self; module ScriptAce; extend Card::Set
# @!visibility ~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/ace_editor/set/self/script_ace.rb ~~
include_set Abstract::CodeFile

Self::ScriptMods.add_to_basket :item_codenames, :script_ace


# @!visibility ~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/ace_editor/set/self/script_ace.rb ~~
end;end;end;end;
