# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module Discussion; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/discussion.rb ~~~~~~~~~~~
def show_comment_box_in_related?
  true
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/discussion.rb ~~~~~~~~~~~
end;end;end;end;
