# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module Salt; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/salt.rb ~~~~~~~~~~~
include All::Permissions::Accounts

view :raw do |args|
  "Private data"
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/salt.rb ~~~~~~~~~~~
end;end;end;end;
