# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module Status; extend Card::Set # ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/status.rb ~~~~~~~~~~~
include All::Permissions::Accounts

def ok_to_update
  if is_own_account? && !Auth.always_ok?
    deny_because you_cant('change the status of your own account')
  else
    super
  end 
end


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/status.rb ~~~~~~~~~~~
end;end;end;end;
