# -*- encoding : utf-8 -*-
class Card; module Set; module Right; module WhenLastEdited; extend Card::Set
# ~~~~~~~~~~~ above autogenerated; below pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/when_last_edited.rb ~~~~~~~~~~~
view :raw do |args|
  card.left.new_card? ? '' : card.left.updated_at.strftime('%A, %B %d, %Y %I:%M %p %Z')
end

view :core, :raw


# ~~~~~~~~~~~ below autogenerated; above pulled from /Users/ethan/dev/wagn/gem/card/mod/05_standard/set/right/when_last_edited.rb ~~~~~~~~~~~
end;end;end;end;
